context:
  name: fio
  version: "3.42"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://github.com/axboe/${{ name }}/archive/refs/tags/${{ name }}-${{ version }}.tar.gz
  sha256: 56b03497a918d07692257890fd759bf73168ad79df5be78a2bcbbdc8ce67895b

build:
  skip:
    - win
  script:
    - ./configure --prefix="${PREFIX}"
    - make install
  number: 0

requirements:
  build:
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
    - make
    - pkg-config
  host:
    - zlib
    - libcurl
    - gnutls
    - if: linux
      then:
        - libnuma
        - libnfs
        - libaio
tests:
  - script:
      - fio --version

about:
  homepage: https://github.com/axboe/fio
  summary: 'Flexible I/O Tester'
  description: |
    Flexible I/O Tester
  license: GPL-2.0-only
  license_file: COPYING
  documentation: https://fio.readthedocs.io/
  repository: https://github.com/axboe/fio
extra:
  recipe-maintainers:
    - ChristianRothQC
